spring:
  application:
    name: User-Service

  datasource:
    url:  jdbc:postgresql://localhost:5432/user_service_db
    username: vicky
    password: Capricon005$
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
